pipeline {
  agent any

  environment {
    PROJECT_NAME_AUTH = "auth-service"
    PROJECT_NAME_FAV = "favorites-service"
  }

  stages {
    stage('Clonar Repositorio') {
      steps {
        git branch: 'backend', url: 'https://github.com/ArturoSolis03/ChefUp-APP.git'
      }
    }

    stage('Build Auth Service') {
      steps {
        dir("backend/${env.PROJECT_NAME_AUTH}") {
          sh "docker build -t ${env.PROJECT_NAME_AUTH}-image ."
        }
      }
    }

    stage('Build Favorites Service') {
      steps {
        dir("backend/${env.PROJECT_NAME_FAV}") {
          sh "docker build -t ${env.PROJECT_NAME_FAV}-image ."
        }
      }
    }

    stage('Run Containers') {
      steps {
        sh "docker run -d --name auth-service -p 3000:3000 ${env.PROJECT_NAME_AUTH}-image"
        sh "docker run -d --name favorites-service -p 3001:3001 ${env.PROJECT_NAME_FAV}-image"
      }
    }
  }

  post {
    success {
      echo "✅ Despliegue exitoso en EC2 con Docker"
    }
    failure {
      echo "❌ Falló el despliegue en EC2"
    }
  }
}