app = "auth-service"

[build]
  image = "node:18-alpine"

[env]
  MONGODB_URI = "mongodb+srv://Cheff:Admin123@cheffupapp.jezpeq5.mongodb.net/?retryWrites=true&w=majority&appName=CheffUpApp"
  ACCESS_TOKEN_SECRET = "admin1"
  ACCESS_TOKEN_EXPIRATION = "1h"
  REFRESH_TOKEN_SECRET = "admin2"
  REFRESH_TOKEN_EXPIRATION = "7d"
  SPOONACULAR_API_KEY = "3d6a46320ba2476bb864cb87058341a5"

[deploy]
  # Opcional, si quieres forzar rollback automático
  strategy = "rolling"